server:
  port: ${PORT:5555}
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:1111}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
ribbon:
  eureka:
    enabled: true
spring:
  datasource:
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.96:3306/udise_shaalakosh
    username: root
    password: abc@123
    
    dbcp2:
      initial-size: 10 
      max-total: 25
      pool-prepared-statements: true